In [ ]:
!pip install faker

Collecting faker
  Downloading Faker-33.1.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: python-dateutil>=2.4 in /usr/local/lib/python3.10/dist-packages (from faker) (2.8.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from faker) (4.12.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.4->faker) (1.17.0)
Downloading Faker-33.1.0-py3-none-any.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 12.2 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-33.1.0

In [ ]:
import pandas as pd
import numpy as np
import csv
from faker import Faker
from faker.providers import address
import random
from datetime import datetime, timedelta

## Creating a customer table

In [ ]:
import csv
import random
from faker import Faker
from faker.providers import address
import pandas as pd

# Inisialisasi Faker
fake = Faker('id_ID')
fake.add_provider(address)

# Set seed untuk menghasilkan data yang konsisten
random.seed(42)  # Anda bisa menggunakan angka lain sebagai seed

# Fungsi untuk menghasilkan nomor telepon dengan kode area +62
def generate_phone_number():
    return f"+62{fake.random_number(digits=10)}"  # atau "0{fake.random_number(digits=10)}"

# Fungsi untuk menghasilkan alamat di Yogyakarta
def generate_yogyakarta_address():
    address_parts = fake.street_address().split(',')
    address_parts[0] += ', Yogyakarta'
    return ', '.join(address_parts)

# Menghasilkan data pelanggan dan langsung mengonversinya ke dalam DataFrame
customers_df = pd.DataFrame(
    [[
        i + 1,  # customer_id
        fake.name(),
        generate_yogyakarta_address(),
        generate_phone_number(),
        fake.email(),
        fake.date_of_birth(minimum_age=17, maximum_age=80).strftime('%Y-%m-%d'),
        fake.random_element(elements=('Male', 'Female'))
    ] for i in range(1500)],
    columns=[
        'customer_id', 'name', 'address', 'phone_number', 'email', 'date_of_birth', 'gender'
    ]
)

# # Menyimpan data ke dalam file CSV
# customers_df.to_csv('customers_yogyakarta.csv', index=False, encoding='utf-8')

print("File 'customers_yogyakarta.csv' telah berhasil dibuat.")

# Menampilkan informasi DataFrame
customers_df.info()

File 'customers_yogyakarta.csv' telah berhasil dibuat.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    1500 non-null   int64
 1   name           1500 non-null   object
 2   address        1500 non-null   object
 3   phone_number   1500 non-null   object
 4   email          1500 non-null   object
 5   date_of_birth  1500 non-null   object
 6   gender         1500 non-null   object
dtypes: int64(1), object(6)
memory usage: 82.2+ KB

In [ ]:
data = pd.DataFrame(customers_df)
data

,customer_id,name,address,phone_number,email,date_of_birth,gender
0,1,"Dr. Jessica Wibisono, S.Sos","Gang Gedebage Selatan No. 6, Yogyakarta",+624410115536,mayasariatma@example.org,2001-02-18,Female
1,2,Emil Simanjuntak,"Jalan Cikutra Barat No. 9, Yogyakarta",+628441266686,irawanokta@example.org,1951-06-06,Male
2,3,"Maryanto Nuraini, S.E.I","Gang Dr. Djunjunan No. 13, Yogyakarta",+62441791659,opheliakuswoyo@example.net,1949-10-21,Female
3,4,Tami Wahyuni,"Jl. Antapani Lama No. 324, Yogyakarta",+627775485262,kayla35@example.net,1955-04-06,Female
4,5,"H. Dagel Waskita, M.Kom.","Gang Pelajar Pejuang No. 63, Yogyakarta",+624739817938,hnugroho@example.com,1979-10-31,Female
...,...,...,...,...,...,...,...
1495,1496,Novi Januar,"Gang W.R. Supratman No. 82, Yogyakarta",+626912677843,atmaja06@example.org,1954-12-25,Female
1496,1497,Nurul Haryanti,"Gg. Jakarta No. 13, Yogyakarta",+621758725743,samiahwijayanti@example.org,2003-07-16,Male
1497,1498,Damar Uyainah,"Gg. Asia Afrika No. 268, Yogyakarta",+627366167186,habibigilda@example.org,2005-06-04,Male
1498,1499,Ani Simbolon,"Gg. Cikutra Barat No. 1, Yogyakarta",+62183080794,darijan99@example.net,2005-01-06,Male
1499,1500,Praba Pratama,"Jalan Wonoayu No. 2, Yogyakarta",+627883418235,michelle42@example.org,1959-02-27,Male

In [ ]:
data.to_csv('customers_yogyakarta.csv', index=False, encoding='utf-8')

In [ ]:
data = pd.read_csv('customers_yogyakarta.csv')
data

,customer_id,name,address,phone_number,email,date_of_birth,gender
0,1,"Dr. Jessica Wibisono, S.Sos","Gang Gedebage Selatan No. 6, Yogyakarta",624410115536,mayasariatma@example.org,2001-02-18,Female
1,2,Emil Simanjuntak,"Jalan Cikutra Barat No. 9, Yogyakarta",628441266686,irawanokta@example.org,1951-06-06,Male
2,3,"Maryanto Nuraini, S.E.I","Gang Dr. Djunjunan No. 13, Yogyakarta",62441791659,opheliakuswoyo@example.net,1949-10-21,Female
3,4,Tami Wahyuni,"Jl. Antapani Lama No. 324, Yogyakarta",627775485262,kayla35@example.net,1955-04-06,Female
4,5,"H. Dagel Waskita, M.Kom.","Gang Pelajar Pejuang No. 63, Yogyakarta",624739817938,hnugroho@example.com,1979-10-31,Female
...,...,...,...,...,...,...,...
1495,1496,Novi Januar,"Gang W.R. Supratman No. 82, Yogyakarta",626912677843,atmaja06@example.org,1954-12-25,Female
1496,1497,Nurul Haryanti,"Gg. Jakarta No. 13, Yogyakarta",621758725743,samiahwijayanti@example.org,2003-07-16,Male
1497,1498,Damar Uyainah,"Gg. Asia Afrika No. 268, Yogyakarta",627366167186,habibigilda@example.org,2005-06-04,Male
1498,1499,Ani Simbolon,"Gg. Cikutra Barat No. 1, Yogyakarta",62183080794,darijan99@example.net,2005-01-06,Male
1499,1500,Praba Pratama,"Jalan Wonoayu No. 2, Yogyakarta",627883418235,michelle42@example.org,1959-02-27,Male

In [ ]:
data_copy = data[data['customer_id']>1000]

In [ ]:
data_copy.to_csv('customers.csv', index=False, encoding='utf-8')

## Creating Account Table

In [ ]:
# Set seed untuk menghasilkan data yang konsisten
random.seed(42)  # Anda bisa menggunakan angka lain sebagai seed

# Fungsi untuk menghasilkan tanggal acak
def random_date(start, end):
    return start + timedelta(days=random.randint(0, (end - start).days))

# Tentukan rentang tanggal
start_date = datetime(2023, 1, 1)
end_date = datetime.now()  # Tanggal saat ini

# Menghasilkan daftar customer_id unik dari 1 hingga 1500
customer_ids = random.sample(range(1, 1501), 1500)

data = []
# Tentukan jumlah akun yang ingin dibuat untuk setiap customer_id
accounts_per_customer = 3  # Misalnya, setiap customer_id memiliki 3 akun

for customer_id in customer_ids:
    for _ in range(accounts_per_customer):
        data.append([
            len(data) + 1,  # account_id (berurutan)
            customer_id,  # customer_id (unik antara 1 dan 1500)
            random.choice(['Savings Account', 'Current Account', 'Fixed Deposit Account']),  # jenis_akun
            round(random.uniform(100000000, 1000000000), 2),  # saldo (acak antara 100.000.000 dan 1.000.000.000)
            random_date(start_date, end_date).strftime('%Y-%m-%d')  # tanggal_pembukaan acak
        ])

with open('accounts.csv', 'w', newline='', encoding='utf-8') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow([
        'account_id', 'customer_id', 'account_type', 'balance', 'opening_date'
    ])
    writer.writerows(data)

print("File 'accounts.csv' telah berhasil dibuat.")

File 'accounts.csv' telah berhasil dibuat.

In [ ]:
data1 = pd.read_csv('accounts.csv')
data1

,account_id,customer_id,account_type,balance,opening_date
0,1,1310,Current Account,6.403691e+08,2023-12-27
1,2,1310,Savings Account,6.201267e+08,2023-08-06
2,3,1310,Savings Account,6.910627e+08,2023-08-18
3,4,229,Savings Account,4.151026e+08,2024-07-23
4,5,229,Current Account,2.033968e+08,2023-10-13
...,...,...,...,...,...
4495,4496,398,Current Account,7.394144e+08,2024-04-18
4496,4497,398,Fixed Deposit Account,6.317062e+08,2024-06-13
4497,4498,1304,Fixed Deposit Account,9.888786e+08,2023-10-01
4498,4499,1304,Savings Account,3.951496e+08,2024-01-19
4499,4500,1304,Fixed Deposit Account,2.306989e+08,2023-02-05

In [ ]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4500 entries, 0 to 4499
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   account_id    4500 non-null   int64
 1   customer_id   4500 non-null   int64
 2   account_type  4500 non-null   object
 3   balance       4500 non-null   float64
 4   opening_date  4500 non-null   object
dtypes: float64(1), int64(2), object(2)
memory usage: 175.9+ KB

In [ ]:
data1[data1['customer_id'] == 1]

,account_id,customer_id,account_type,balance,opening_date
1449,1450,1,Fixed Deposit Account,6.023274e+08,2023-04-19
1450,1451,1,Fixed Deposit Account,6.189073e+08,2024-11-21
1451,1452,1,Current Account,7.322954e+08,2024-03-13

## Creating a transaction table

In [ ]:
# Set seed to generate consistent data
random.seed(42)

# Function to generate transaction type
def generate_transaction_type(account_type):
    if account_type == 'Savings Account':
        return random.choice(['Deposit', 'Withdrawal'])
    elif account_type == 'Current Account':
        return random.choice(['Deposit', 'Withdrawal', 'Transfer'])
    elif account_type == 'Fixed Deposit Account':
        return random.choice(['Deposit', 'Withdrawal'])
    return 'Deposit'  # Default

# Function to generate transaction amount
def generate_transaction_amount(account_type):
    if account_type == 'Savings Account':
        return round(random.uniform(100000, 10000000), 2)  # 100,000 - 10,000,000
    elif account_type == 'Current Account':
        return round(random.uniform(50000, 5000000), 2)  # 50,000 - 5,000,000
    elif account_type == 'Fixed Deposit Account':
        return round(random.uniform(1000000, 100000000), 2)  # 1,000,000 - 100,000,000
    return 0.0  # Default

# Function to generate random date and time
def generate_datetime(start_date, end_date):
    time_between_dates = end_date - start_date
    seconds_between_dates = time_between_dates.total_seconds()
    random_number_of_seconds = random.randrange(int(seconds_between_dates))
    random_datetime = start_date + timedelta(seconds=random_number_of_seconds)
    return random_datetime

# Read accounts from CSV file
accounts = []
with open('accounts.csv', 'r', encoding='utf-8') as file:
    reader = csv.reader(file)
    next(reader)  # Skip header
    for row in reader:
        account_id = int(row[0])  # Parse account_id as integer
        if 1 <= account_id <= 4500:  # Ensure account_id is within the range 1 to 4500
            accounts.append(row)

transactions = []
transaction_id = 1
start_date = datetime(2023, 1, 1, 0, 0, 0)  # Start from January 1, 2023, at 00:00:00
end_date = datetime(2024, 1, 1, 0, 0, 0)  # Until January 1, 2024, at 00:00:00

# Generate transactions
for i in range(10000):  # 10,000 transactions
    account_index = random.randint(0, len(accounts) - 1)
    account_id = accounts[account_index][0]
    account_type = accounts[account_index][2]
    opening_date = datetime.strptime(accounts[account_index][4], '%Y-%m-%d')  # Opening date

    # Ensure opening_date is not greater than end_date
    if opening_date >= end_date:
        continue  # Skip this iteration if opening date is greater than or equal to the end date

    transaction_type = generate_transaction_type(account_type)
    amount = generate_transaction_amount(account_type)

    # Generate a valid transaction date
    transaction_date = generate_datetime(opening_date, end_date)  # Ensure transaction date >= opening date

    transactions.append([
        transaction_id,
        account_id,
        transaction_type,
        amount,
        transaction_date.strftime("%Y-%m-%d %H:%M:%S")  # Format date
    ])
    transaction_id += 1

# Save transactions to CSV file
with open('transactions_consistent.csv', 'w', newline='', encoding='utf-8') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow([
        'transaction_id', 'account_id', 'transaction_type', 'amount', 'transaction_date'
    ])
    writer.writerows(transactions)

print("File 'transactions_consistent.csv' has been successfully created.")

File 'transactions_consistent.csv' has been successfully created.

In [ ]:
data2 = pd.read_csv('transactions_consistent.csv')
data2

,transaction_id,account_id,transaction_type,amount,transaction_date
0,1,205,Transfer,1411395.13,2023-11-28 16:07:07
1,2,1144,Transfer,557351.12,2023-11-18 10:34:55
2,3,261,Deposit,10275828.75,2023-05-23 08:33:24
3,4,3680,Transfer,1427044.01,2023-04-15 12:34:22
4,5,2788,Withdrawal,1639247.05,2023-12-26 03:04:12
...,...,...,...,...,...
4856,4857,2377,Deposit,3940535.12,2023-02-03 05:08:55
4857,4858,1638,Transfer,3630516.40,2023-10-23 18:11:07
4858,4859,3284,Withdrawal,47286324.43,2023-09-11 06:57:48
4859,4860,4395,Withdrawal,3975008.50,2023-12-05 20:54:56
4860,4861,2659,Transfer,2170487.65,2023-06-25 08:43:41

In [ ]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4861 entries, 0 to 4860
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    4861 non-null   int64
 1   account_id        4861 non-null   int64
 2   transaction_type  4861 non-null   object
 3   amount            4861 non-null   float64
 4   transaction_date  4861 non-null   object
dtypes: float64(1), int64(2), object(2)
memory usage: 190.0+ KB

## Creating a loan table

In [ ]:
import csv
import random
from datetime import datetime, timedelta

# Set seed to ensure consistent data generation
random.seed(42)  # You can use a different number as the seed

def generate_loan_amount():
    return round(random.uniform(1000000, 10000000), 2)  # Loan amount between 1,000,000 and 10,000,000

def generate_loan_date(account_opening_date, end_date):
    # Generate a loan date that is later than the account opening date
    time_between_dates = end_date - account_opening_date
    if time_between_dates.days <= 0:
        return None  # Return None if there is no valid date range
    random_number_of_days = random.randrange(1, time_between_dates.days + 1)  # At least 1 day after the opening date
    random_date = account_opening_date + timedelta(days=random_number_of_days)
    return random_date.strftime("%Y-%m-%d")

def generate_loan_term():
    return random.randint(12, 60)  # Loan term between 12 and 60 months

accounts = []
with open('accounts.csv', 'r', encoding='utf-8') as file:
    reader = csv.reader(file)
    next(reader)  # Skip header
    for row in reader:
        accounts.append(row)

loans = []
loan_id = 1500  # Start loan_id from 1500
customer_ids = set()  # Ensure each customer has only one loan

end_date = datetime(2024, 1, 1)

for account in accounts:
    customer_id = int(account[1])  # Retrieve customer_id as an integer
    account_opening_date = datetime.strptime(account[4], "%Y-%m-%d")  # Parse account opening date
    if customer_id not in customer_ids and 1 <= customer_id <= 1500:  # Ensure customer_id is within the specified range
        loan_amount = generate_loan_amount()
        loan_date = generate_loan_date(account_opening_date, end_date)  # Generate the loan date
        if loan_date is not None:  # Ensure the loan_date is valid
            loan_term = generate_loan_term()
            loans.append([
                loan_id,
                customer_id,
                loan_amount,
                loan_date,
                loan_term
            ])
            customer_ids.add(customer_id)
            loan_id += 1  # Increment loan_id for the next loan

with open('loans.csv', 'w', newline='', encoding='utf-8') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow([
        'loan_id', 'customer_id', 'loan_amount', 'loan_date', 'loan_term_months'
    ])
    writer.writerows(loans)

print("The file 'loans.csv' has been successfully created.")

The file 'loans.csv' has been successfully created.

In [ ]:
data3 = pd.read_csv('loans.csv')
data3

      loan_id  customer_id  loan_amount   loan_date  loan_term_months
0        1500         1310   6754841.19  2023-12-28                59
1        1501          229   3008896.64  2023-10-27                55
2        1502          564   1286044.12  2023-07-28                25
3        1503          458   7311924.76  2023-12-13                26
4        1504          286   5042881.42  2023-07-16                12
...       ...          ...          ...         ...               ...
1322     2822         1114   5390585.94  2023-11-01                47
1323     2823          550   7203249.82  2023-08-27                58
1324     2824          387   2212589.56  2023-04-29                43
1325     2825          398   7359633.81  2023-12-11                30
1326     2826         1304   5884606.69  2023-12-03                24

[1327 rows x 5 columns]

In [ ]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1327 entries, 0 to 1326
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   loan_id           1327 non-null   int64
 1   customer_id       1327 non-null   int64
 2   loan_amount       1327 non-null   float64
 3   loan_date         1327 non-null   object
 4   loan_term_months  1327 non-null   int64
dtypes: float64(1), int64(3), object(1)
memory usage: 52.0+ KB